#!/bin/bash

DIR0="/opt"
DIR1="opencv"
DIR2="build"

# Verify requisites

if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root!"
        exit 1
fi

wget -q --spider http://www.google.com
if [ "$?" != 0 ]; then
        echo "This script must be run with internet connection!"
        exit 1
fi

Update/upgrade the system and install required packages

apt-get -y update
apt-get -y upgrade
apt-get -y install build-essential cmake pkg-config
sudo apt-get -y install libtiff4-dev libjpeg-dev libjasper-dev libpng12-dev
sudo apt-get -y install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
apt-get -y autoremove
apt-get -y autoclean
apt-get -y clean


# Clone and install

cd $DIR0

if [ -d $DIR1 ]; then
    rm -r $DIR1
    echo "Old opencv directory removed"
fi

git clone https://github.com/Itseez/opencv.git
cd opencv

# git checkout master
git checkout tags/2.4.10

if [ -d $DIR2 ]; then
    rm -r $DIR2
    echo "Old build directory removed"
fi

mkdir build
cd build
# cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_CUDA=OFF -D WITH_CUFFT=OFF -D WITH_CUBLAS=OFF -D WITH_NVCUVID=OFF -D WITH_OPENCL=OFF -D WITH_OPENCLAMDFFT=OFF -D WITH_OPENCLAMDBLAS=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D ENABLE_NEON=ON ..
cmake -D CMAKE_C_FLAGS='-O3 -mfpu=neon -mfloat-abi=hard' -D CMAKE_CXX_FLAGS='-O3 -mfpu=neon -mfloat-abi=hard' -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -DENABLE_VFPV3=ON -DENABLE_NEON=ON ..
make -j $(nproc)
make install

sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
sudo ldconfig

echo "OpenCV installed."
echo "You must reboot for the changes take effect!"
