#!/bin/bash

DIR0="/opt"
DIR1="opencv"
DIR2="build"

# Verify requisites

if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root!"
        exit 1
fi

wget -q --spider http://www.google.com
if [ "$?" != 0 ]; then
        echo "This script must be run with internet connection!"
        exit 1
fi

# Update/upgrade the system and install required packages

apt-get -y update
apt-get -y upgrade
apt-get -y install libopencv-dev build-essential cmake git libgtk2.0-dev pkg-config python-dev python-numpy libdc1394-22 libdc1394-22-dev libjpeg-dev libpng12-dev libtiff4-dev libjasper-dev libavcodec-dev libavformat-dev libswscale-dev libxine-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libv4l-dev libtbb-dev libqt4-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils unzip

# Clone and install

cd $DIR0

if [ -d $DIR1 ]; then
    rm -r $DIR1
    echo "Old opencv directory removed"
fi

git clone https://github.com/Itseez/opencv.git
cd opencv

if [ -d $DIR2 ]; then
    rm -r $DIR2
    echo "Old build directory removed"
fi

mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
make -j $(nproc)
make install

sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
sudo ldconfig

echo "OpenCV installed."
echo "You must reboot for the changes take effect!"
