#!/bin/bash

DIR="/opt/opencv"

if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root!"
        exit 1
fi

if [ -d $DIR ]; then
    rm -r $DIR
    echo "opencv directory removed"
fi

echo "Opencv uninstalled."
